---
- name: "Update /etc/hostname"
  template:
    src:  "{{ item.src | default((item.dest | basename ()) + '.j2')}}"
    dest: "{{ item.dest }}"
  with_items:
    - dest:  "/etc/hostname"
  notify: "reboot"
  when:
    - "inventory_hostname is defined"
  tags:
    - "hostname"
